app = "whatsapp-chatgpt-bot"

[build]
  image = "python:3.11"

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
